# Generated by Django 4.1.6 on 2023-03-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_wiki_app', '0003_alter_imageinfo_upload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='src',
            field=models.ImageField(default='', upload_to='meme_image/', verbose_name='表情包存储路径'),
        ),
    ]
