# Generated by Django 4.1.6 on 2023-03-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_wiki_app', '0004_alter_imageinfo_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='src',
            field=models.ImageField(default='', unique=True, upload_to='meme_image/', verbose_name='表情包存储路径'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
